version: '3.3'

services:
  web:
    image: node:18.17.0-alpine
    working_dir: /app
    user: node
    expose:
      - 8080
    labels:
      - "traefik.http.routers.whoami.entrypoints=https, http"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.rule=Host(`versa.test`)"
      - "traefik.http.services.whoami-service.loadbalancer.server.port=8080"

    volumes:
      - ./:/app:z

networks:
  default:
    driver: bridge
    external:
      name: dev-network
